<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>false</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>XivAuth.Testing</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Auth0.AuthenticationApi" Version="7.43.0" />
    <PackageReference Include="Auth0.Core" Version="7.43.0" />
    <PackageReference Include="Duende.IdentityModel" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XIVAuthClient\XIVAuthClient.csproj" />
  </ItemGroup>

</Project>
